### ISSUE TITLE
Git dirty indicator is not showing up.

### ISSUE THREAD

**Issue by berkant** [oh-my-fish/theme-robbyrussell#4]
The yellow X is not appearing when I'm in a dirty git repo. I guess something's wrong with `_is_git_dirty` function.

```fish
function _is_git_dirty
  set -l show_untracked (git config --bool bash.showUntrackedFiles)
  set untracked ''
  if [ "$theme_display_git_untracked" = 'no' -o "$show_untracked" = 'false' ]
    set untracked '--untracked-files=no'
  end
  echo (command git status -s --ignore-submodules=dirty $untracked 2> /dev/null)
end
```

When I remove the stderr redirection (`2>/dev/null`), git complains as `empty string is not a valid pathspec`. I just commented the `set untracked ''` line out and it's working now. Could you reproduce the same?

What's better is #2 fixes this. Why not merging it?

**Comment by cr0t** [comment]
@bobthecow Any activity here? Or I can close the PR #2 ?

**Comment by scorphus** [comment]
Thanks for reporting, @berkant. And sorry for the delay.

Please, check if the fix works for you. Thanks in advance.
